import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import { Download, Loader2, CheckCircle2, Package, Smartphone, Code2, Apple } from "lucide-react";
import JSZip from "jszip";
import SetupGuideModal from "@/components/dashboard/SetupGuideModal";
import CodemagicPanel from "@/components/dashboard/CodemagicPanel";

const buildTypes = [
  {
    id: "apk",
    label: "Android APK",
    desc: "Direct install on Android devices",
    icon: Smartphone,
    color: "from-green-600 to-emerald-600",
    glow: "shadow-emerald-500/20",
    cmd: "flutter build apk --release",
  },
  {
    id: "aab",
    label: "Android AAB",
    desc: "Google Play Store upload bundle",
    icon: Package,
    color: "from-blue-600 to-cyan-600",
    glow: "shadow-blue-500/20",
    cmd: "flutter build appbundle --release",
  },
  {
    id: "ios",
    label: "iOS / Xcode",
    desc: "Xcode project for App Store",
    icon: Apple,
    color: "from-gray-600 to-slate-600",
    glow: "shadow-slate-500/20",
    cmd: "flutter build ios --release",
  },
  {
    id: "source",
    label: "Flutter Source",
    desc: "Complete Flutter project ZIP",
    icon: Code2,
    color: "from-violet-600 to-fuchsia-600",
    glow: "shadow-violet-500/20",
    cmd: "Full project zip",
  },
];

function buildZip(project) {
  const appName = project.analysis?.siteName || project.name || "app";
  const safeAppName = appName.replace(/[^a-z0-9]/gi, "_").toLowerCase();
  const code = project.flutter_code || "// No code generated yet";

  const pubspec = `name: ${safeAppName}
description: Generated Flutter app from ${project.url}
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
`;

  const androidManifest = `<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:label="${appName}"
        android:name="\${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>`;

  const githubWorkflow = `name: Flutter Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-apk:
    name: Build APK & AAB
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab
`;

  const readme = `# ${appName} - Flutter App

Generated by WebApp Converter AI from: ${project.url}

## Quick Start

### 1. Install Flutter SDK
https://flutter.dev/docs/get-started/install

### 2. Get dependencies
\`\`\`bash
cd ${safeAppName}
flutter pub get
\`\`\`

### 3. Run on device/emulator
\`\`\`bash
flutter run
\`\`\`

### 4. Build release APK
\`\`\`bash
flutter build apk --release
# Output: build/app/outputs/flutter-apk/app-release.apk
\`\`\`

### Online alternative
Upload this project to https://flutlab.io to build in the browser.
`;

  const zip = new JSZip();
  zip.folder("lib").file("main.dart", code);
  zip.file("pubspec.yaml", pubspec);
  zip.file("README.md", readme);
  zip.folder(".github").folder("workflows").file("flutter-build.yml", githubWorkflow);
  zip.folder("android").folder("app").folder("src").folder("main").file("AndroidManifest.xml", androidManifest);

  return { zip, safeAppName, appName, folder: zip };
}

export default function BuildPanel({ project, onBuild, isBuilding }) {
  const [showGuide, setShowGuide] = useState(false);
  const [downloadingSource, setDownloadingSource] = useState(false);
  const buildStatus = project.build_status || {};

  const appName = project.analysis?.siteName || project.name || "app";

  const handleDownloadZip = async () => {
    setDownloadingSource(true);
    const { zip, safeAppName } = buildZip(project);
    const blob = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${safeAppName}_flutter.zip`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setDownloadingSource(false);
    setShowGuide(true);
  };

  const handleBuildWithGuide = async (id) => {
    await onBuild(id);
    setShowGuide(true);
  };

  return (
    <div className="space-y-6 max-w-2xl">
      <div>
        <h2 className="text-base font-semibold text-slate-900 mb-1">Build & Download</h2>
        <p className="text-sm text-slate-500">Download your Flutter project as a ZIP and build locally</p>
      </div>

      {/* Build cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {buildTypes.map(bt => {
          const status = buildStatus[bt.id];
          const isBuildingThis = status === "building";
          const isReady = status === "ready";
          const isSourceCard = bt.id === "source";

          return (
            <div
              key={bt.id}
              className="bg-slate-50 border border-slate-100 rounded-2xl p-5 hover:bg-slate-100 transition-colors"
            >
              <div className="flex items-start justify-between mb-4">
                <div className={`w-10 h-10 rounded-xl bg-gradient-to-br ${bt.color} flex items-center justify-center shadow-lg ${bt.glow}`}>
                  <bt.icon className="w-5 h-5 text-white" />
                </div>
                {isReady && (
                  <span className="flex items-center gap-1 text-[10px] text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-2 py-1 rounded-full">
                    <CheckCircle2 className="w-3 h-3" />
                    Ready
                  </span>
                )}
              </div>

              <p className="text-sm font-semibold text-slate-900 mb-1">{bt.label}</p>
              <p className="text-xs text-slate-500 mb-1">{bt.desc}</p>
              <p className="text-[10px] text-slate-400 font-mono mb-4">{bt.cmd}</p>

              {isSourceCard ? (
                <Button
                  onClick={handleDownloadZip}
                  disabled={downloadingSource}
                  size="sm"
                  className="w-full bg-violet-600 hover:bg-violet-500 text-white text-xs"
                >
                  {downloadingSource ? (
                    <><Loader2 className="w-3.5 h-3.5 mr-1.5 animate-spin" />Preparing ZIP...</>
                  ) : (
                    <><Download className="w-3.5 h-3.5 mr-1.5" />Download ZIP</>
                  )}
                </Button>
              ) : isReady ? (
                <Button
                  onClick={handleDownloadZip}
                  size="sm"
                  className="w-full bg-emerald-600 hover:bg-emerald-500 text-white text-xs"
                >
                  <Download className="w-3.5 h-3.5 mr-1.5" />
                  Download ZIP
                </Button>
              ) : (
                <Button
                  onClick={() => handleBuildWithGuide(bt.id)}
                  disabled={isBuildingThis || isBuilding || project.status === "analyzing"}
                  size="sm"
                  variant="outline"
                  className="w-full text-xs"
                >
                  {isBuildingThis ? (
                    <><Loader2 className="w-3.5 h-3.5 mr-1.5 animate-spin" />Building...</>
                  ) : (
                    "Build Now"
                  )}
                </Button>
              )}
            </div>
          );
        })}
      </div>

      {/* Codemagic CI/CD */}
      <div className="border border-slate-100 rounded-2xl p-5 bg-slate-50">
        <CodemagicPanel />
      </div>

      <SetupGuideModal
        open={showGuide}
        onClose={() => setShowGuide(false)}
        appName={appName}
      />
    </div>
  );
}